feat: separate CLI Tutor Mode helptext
ipfs-shipyard/ipfs-webui pull request #1700
Opened 2020-12-17 18:47 UTC by jessicaschilling

Closes https://github.com/ipfs-shipyard/ipfs-webui/issues/1686.

This PR separates out the i18n key `cliModal.extraNotes` so we can display different CLI Tutor Mode modal helptext in different situations:
- "IPFS Config" modal (already existed)
- "Set Pinning" command in Files screen context menu (new in this PR)

2020-12-28 16:12 UTC, rafaelramalho19 approved these changes

2020-12-28 16:26 UTC, jessicaschilling commented
Thanks, @rafaelramalho19, but can you please look at the "to do" item when you get a chance? Thank you!

2020-12-31 15:38 UTC, rafaelramalho19 commented
@jessicaschilling by help text you mean the `title` html attribute?

2020-12-31 15:50 UTC, jessicaschilling commented
@rafaelramalho19 - cliModal.ExtraNotes is customized as part of this work (that's the helptext), but I can't get it to display conditionally for the "Set pinning" command under the "three dots" context menu.

2021-01-04 21:47 UTC, jessicaschilling commented
Thanks, @rafaelramalho19!

@lidel - can you please have a look when you get the chance? Would be one more item done in the pinning epic ...

2021-01-05 13:53 UTC, lidel requested changes
LGTM but we should make key names more explicit, 
will save us time when debugging bugs in the future :)

@jessicaschilling mind updating places where below keys are used?

2021-01-05 13:53 UTC, lidel commented on public/locales/en/files.json
> +    "extraNotes": "This command is only for local pinning/unpinning. If you want to use a remote pinning service, consult that service's documentation to learn how to pin/unpin from the command line.
```suggestion
    "extraNotesPinning": "This command is only for local pinning/unpinning. If you want to use a remote pinning service, consult that service's documentation to learn how to pin/unpin from the command line."
```

2021-01-05 13:53 UTC, lidel commented on public/locales/en/settings.json
> +    "extraNotes": "If you've made changes to the config in this page's code editor that you'd like to save, click the download icon next to the copy button to download it as a JSON file."
```suggestion
    "extraNotesJsonConfig": "If you've made changes to the config in this page's code editor that you'd like to save, click the download icon next to the copy button to download it as a JSON file."
```

2021-01-05 15:34 UTC, jessicaschilling commented
@lidel - good call. Updated. Please merge at your leisure ...

2021-01-05 16:23 UTC, merged